name: CI/CD for Jozo Music Control

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/jozo-music-control:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/jozo-music-control:latest

      # 5. Deploy Docker container (Staging hoặc Production)
      - name: Deploy Docker container
        if: github.ref_name == 'main' || github.ref_name == 'develop'
        run: |
          docker stop jozo-music-control || true && docker rm jozo-music-control || true
          docker run -d \
            --name jozo-music-control \
            -p 5000:3000 \
            ${{ secrets.DOCKER_USERNAME }}/jozo-music-control:${{ github.ref_name }}
