name: CI/CD for Jozo Music Control

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Xác định tên file env dựa trên branch
      - name: Set environment file variable
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "ENV_FILE=.env.production" >> $GITHUB_ENV
          else
            echo "ENV_FILE=.env.development" >> $GITHUB_ENV
          fi

      # 3. Tạo file env từ secret (không commit file env vào repo)
      - name: Create environment file for build
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "${{ secrets.ENV_PRODUCTION }}" > .env.production
          else
            echo "${{ secrets.ENV_DEVELOPMENT }}" > .env.development
          fi

      # 4. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 5. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build Docker image và push lên Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: ENV_FILE=${{ env.ENV_FILE }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/jozo-music-control:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/jozo-music-control:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1. Kết nối SSH đến VPS và deploy container
      - name: Connect to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Login Docker Hub trên VPS
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            # Tạo file env trên VPS từ secret
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              echo "${{ secrets.ENV_PRODUCTION }}" > /tmp/.env.production
              ENV_FILE="/tmp/.env.production"
            else
              echo "${{ secrets.ENV_DEVELOPMENT }}" > /tmp/.env.development
              ENV_FILE="/tmp/.env.development"
            fi

            # Pull image mới, dừng container cũ và chạy container mới với --env-file
            docker pull ${{ secrets.DOCKER_USERNAME }}/jozo-music-control:${{ github.ref_name }}
            docker stop jozo-music-control || true
            docker rm jozo-music-control || true
            docker run -d \
              --name jozo-music-control \
              --env-file $ENV_FILE \
              -p 3000:3000 \
              ${{ secrets.DOCKER_USERNAME }}/jozo-music-control:${{ github.ref_name }}
