name: CI/CD for Jozo Music Control

on:
  push:
    branches:
      - main
      - develop

jobs:
  # Job 1: Build Docker Image
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build Docker image and push to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/jozo-music-control:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/jozo-music-control:latest

  # Job 2: Deploy to Staging or Production
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1. Kết nối SSH đến VPS
      - name: Connect to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Login to Docker Hub
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            # Pull và chạy container mới
            docker pull ${{ secrets.DOCKER_USERNAME }}/jozo-music-control:${{ github.ref_name }}
            docker stop jozo-music-control || true
            docker rm jozo-music-control || true
            docker run -d \
              --name jozo-music-control \
              -p 3000:3000 \
              ${{ secrets.DOCKER_USERNAME }}/jozo-music-control:${{ github.ref_name }}
