name: Pull Request Build Check

on:
  pull_request:
    branches-ignore:
      - main
      - develop

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the project
      - name: Build the project
        run: npm run build

      # 5. Run linting and tests (optional)
      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test
